import numpy as np


Kp = np.zeros((66, 1))
Ki = np.zeros((66, 1))
Kd = np.zeros((66, 1))

#----------------------------------------Kp-----------------------------------------------------
avatar_gofa1_joint_1_q_kp = 6
avatar_gofa1_joint_2_q_kp = 6
avatar_gofa1_joint_3_q_kp = 6
avatar_gofa1_joint_4_q_kp = 6
avatar_gofa1_joint_5_q_kp = 6
avatar_gofa1_joint_6_q_kp = 6

avatar_lh_WRJ2_q_kp = 6
avatar_lh_WRJ1_q_kp = 6
avatar_lh_FFJ4_q_kp = 6
avatar_lh_FFJ3_q_kp = 6
avatar_lh_FFJ2_q_kp = 6
avatar_lh_FFJ1_q_kp = 6
avatar_lh_MFJ4_q_kp = 6
avatar_lh_MFJ3_q_kp = 6
avatar_lh_MFJ2_q_kp = 6
avatar_lh_MFJ1_q_kp = 6
avatar_lh_RFJ4_q_kp = 6
avatar_lh_RFJ3_q_kp = 6
avatar_lh_RFJ2_q_kp = 6
avatar_lh_RFJ1_q_kp = 6
avatar_lh_LFJ5_q_kp = 6
avatar_lh_LFJ4_q_kp = 6
avatar_lh_LFJ3_q_kp = 6
avatar_lh_LFJ2_q_kp = 6
avatar_lh_LFJ1_q_kp = 6
avatar_lh_THJ5_q_kp = 6
avatar_lh_THJ4_q_kp = 6
avatar_lh_THJ3_q_kp = 6
avatar_lh_THJ2_q_kp = 6
avatar_lh_THJ1_q_kp = 6

avatar_xarm6_joint1_q_kp = 6
avatar_xarm6_joint2_q_kp = 6
avatar_xarm6_joint3_q_kp = 6
avatar_xarm6_joint4_q_kp = 6
avatar_xarm6_joint5_q_kp = 6
avatar_xarm6_joint6_q_kp = 6

avatar_gofa2_joint_1_q_kp = avatar_gofa1_joint_1_q_kp
avatar_gofa2_joint_2_q_kp = avatar_gofa1_joint_2_q_kp
avatar_gofa2_joint_3_q_kp = avatar_gofa1_joint_3_q_kp
avatar_gofa2_joint_4_q_kp = avatar_gofa1_joint_4_q_kp
avatar_gofa2_joint_5_q_kp = avatar_gofa1_joint_5_q_kp
avatar_gofa2_joint_6_q_kp = avatar_gofa1_joint_6_q_kp

avatar_rh_WRJ2_q_kp = avatar_lh_WRJ2_q_kp
avatar_rh_WRJ1_q_kp = avatar_lh_WRJ1_q_kp
avatar_rh_FFJ4_q_kp = avatar_lh_FFJ4_q_kp
avatar_rh_FFJ3_q_kp = avatar_lh_FFJ3_q_kp
avatar_rh_FFJ2_q_kp = avatar_lh_FFJ2_q_kp
avatar_rh_FFJ1_q_kp = avatar_lh_FFJ1_q_kp
avatar_rh_MFJ4_q_kp = avatar_lh_MFJ4_q_kp
avatar_rh_MFJ3_q_kp = avatar_lh_MFJ3_q_kp
avatar_rh_MFJ2_q_kp = avatar_lh_MFJ2_q_kp
avatar_rh_MFJ1_q_kp = avatar_lh_MFJ1_q_kp
avatar_rh_RFJ4_q_kp = avatar_lh_RFJ4_q_kp
avatar_rh_RFJ3_q_kp = avatar_lh_RFJ3_q_kp
avatar_rh_RFJ2_q_kp = avatar_lh_RFJ2_q_kp
avatar_rh_RFJ1_q_kp = avatar_lh_RFJ1_q_kp
avatar_rh_LFJ5_q_kp = avatar_lh_LFJ5_q_kp
avatar_rh_LFJ4_q_kp = avatar_lh_LFJ4_q_kp
avatar_rh_LFJ3_q_kp = avatar_lh_LFJ3_q_kp
avatar_rh_LFJ2_q_kp = avatar_lh_LFJ2_q_kp
avatar_rh_LFJ1_q_kp = avatar_lh_LFJ1_q_kp
avatar_rh_THJ5_q_kp = avatar_lh_THJ5_q_kp
avatar_rh_THJ4_q_kp = avatar_lh_THJ4_q_kp
avatar_rh_THJ3_q_kp = avatar_lh_THJ3_q_kp
avatar_rh_THJ2_q_kp = avatar_lh_THJ2_q_kp
avatar_rh_THJ1_q_kp = avatar_lh_THJ1_q_kp
#----------------------------------------Ki-----------------------------------------------------
avatar_gofa1_joint_1_q_ki = 0
avatar_gofa1_joint_2_q_ki = 0
avatar_gofa1_joint_3_q_ki = 0
avatar_gofa1_joint_4_q_ki = 0
avatar_gofa1_joint_5_q_ki = 0
avatar_gofa1_joint_6_q_ki = 0

avatar_lh_WRJ2_q_ki = 0
avatar_lh_WRJ1_q_ki = 0
avatar_lh_FFJ4_q_ki = 0
avatar_lh_FFJ3_q_ki = 0
avatar_lh_FFJ2_q_ki = 0
avatar_lh_FFJ1_q_ki = 0
avatar_lh_MFJ4_q_ki = 0
avatar_lh_MFJ3_q_ki = 0
avatar_lh_MFJ2_q_ki = 0
avatar_lh_MFJ1_q_ki = 0
avatar_lh_RFJ4_q_ki = 0
avatar_lh_RFJ3_q_ki = 0
avatar_lh_RFJ2_q_ki = 0
avatar_lh_RFJ1_q_ki = 0
avatar_lh_LFJ5_q_ki = 0
avatar_lh_LFJ4_q_ki = 0
avatar_lh_LFJ3_q_ki = 0
avatar_lh_LFJ2_q_ki = 0
avatar_lh_LFJ1_q_ki = 0
avatar_lh_THJ5_q_ki = 0
avatar_lh_THJ4_q_ki = 0
avatar_lh_THJ3_q_ki = 0
avatar_lh_THJ2_q_ki = 0
avatar_lh_THJ1_q_ki = 0

avatar_xarm6_joint1_q_ki = 0
avatar_xarm6_joint2_q_ki = 0
avatar_xarm6_joint3_q_ki = 0
avatar_xarm6_joint4_q_ki = 0
avatar_xarm6_joint5_q_ki = 0
avatar_xarm6_joint6_q_ki = 0

avatar_gofa2_joint_1_q_ki = avatar_gofa1_joint_1_q_ki
avatar_gofa2_joint_2_q_ki = avatar_gofa1_joint_2_q_ki
avatar_gofa2_joint_3_q_ki = avatar_gofa1_joint_3_q_ki
avatar_gofa2_joint_4_q_ki = avatar_gofa1_joint_4_q_ki
avatar_gofa2_joint_5_q_ki = avatar_gofa1_joint_5_q_ki
avatar_gofa2_joint_6_q_ki = avatar_gofa1_joint_6_q_ki

avatar_rh_WRJ2_q_ki = avatar_lh_WRJ2_q_ki
avatar_rh_WRJ1_q_ki = avatar_lh_WRJ1_q_ki
avatar_rh_FFJ4_q_ki = avatar_lh_FFJ4_q_ki
avatar_rh_FFJ3_q_ki = avatar_lh_FFJ3_q_ki
avatar_rh_FFJ2_q_ki = avatar_lh_FFJ2_q_ki
avatar_rh_FFJ1_q_ki = avatar_lh_FFJ1_q_ki
avatar_rh_MFJ4_q_ki = avatar_lh_MFJ4_q_ki
avatar_rh_MFJ3_q_ki = avatar_lh_MFJ3_q_ki
avatar_rh_MFJ2_q_ki = avatar_lh_MFJ2_q_ki
avatar_rh_MFJ1_q_ki = avatar_lh_MFJ1_q_ki
avatar_rh_RFJ4_q_ki = avatar_lh_RFJ4_q_ki
avatar_rh_RFJ3_q_ki = avatar_lh_RFJ3_q_ki
avatar_rh_RFJ2_q_ki = avatar_lh_RFJ2_q_ki
avatar_rh_RFJ1_q_ki = avatar_lh_RFJ1_q_ki
avatar_rh_LFJ5_q_ki = avatar_lh_LFJ5_q_ki
avatar_rh_LFJ4_q_ki = avatar_lh_LFJ4_q_ki
avatar_rh_LFJ3_q_ki = avatar_lh_LFJ3_q_ki
avatar_rh_LFJ2_q_ki = avatar_lh_LFJ2_q_ki
avatar_rh_LFJ1_q_ki = avatar_lh_LFJ1_q_ki
avatar_rh_THJ5_q_ki = avatar_lh_THJ5_q_ki
avatar_rh_THJ4_q_ki = avatar_lh_THJ4_q_ki
avatar_rh_THJ3_q_ki = avatar_lh_THJ3_q_ki
avatar_rh_THJ2_q_ki = avatar_lh_THJ2_q_ki
avatar_rh_THJ1_q_ki = avatar_lh_THJ1_q_ki
#----------------------------------------Kd-----------------------------------------------------
avatar_gofa1_joint_1_q_kd = 7
avatar_gofa1_joint_2_q_kd = 7
avatar_gofa1_joint_3_q_kd = 7
avatar_gofa1_joint_4_q_kd = 7
avatar_gofa1_joint_5_q_kd = 7
avatar_gofa1_joint_6_q_kd = 7

avatar_lh_WRJ2_q_kd = 7
avatar_lh_WRJ1_q_kd = 7
avatar_lh_FFJ4_q_kd = 7
avatar_lh_FFJ3_q_kd = 7
avatar_lh_FFJ2_q_kd = 7
avatar_lh_FFJ1_q_kd = 7
avatar_lh_MFJ4_q_kd = 7
avatar_lh_MFJ3_q_kd = 7
avatar_lh_MFJ2_q_kd = 7
avatar_lh_MFJ1_q_kd = 7
avatar_lh_RFJ4_q_kd = 7
avatar_lh_RFJ3_q_kd = 7
avatar_lh_RFJ2_q_kd = 7
avatar_lh_RFJ1_q_kd = 7
avatar_lh_LFJ5_q_kd = 7
avatar_lh_LFJ4_q_kd = 7
avatar_lh_LFJ3_q_kd = 7
avatar_lh_LFJ2_q_kd = 7
avatar_lh_LFJ1_q_kd = 7
avatar_lh_THJ5_q_kd = 7
avatar_lh_THJ4_q_kd = 7
avatar_lh_THJ3_q_kd = 7
avatar_lh_THJ2_q_kd = 7
avatar_lh_THJ1_q_kd = 7

avatar_xarm6_joint1_q_kd = 7
avatar_xarm6_joint2_q_kd = 7
avatar_xarm6_joint3_q_kd = 7
avatar_xarm6_joint4_q_kd = 7
avatar_xarm6_joint5_q_kd = 7
avatar_xarm6_joint6_q_kd = 7

avatar_gofa2_joint_1_q_kd = avatar_gofa1_joint_1_q_kd
avatar_gofa2_joint_2_q_kd = avatar_gofa1_joint_2_q_kd
avatar_gofa2_joint_3_q_kd = avatar_gofa1_joint_3_q_kd
avatar_gofa2_joint_4_q_kd = avatar_gofa1_joint_4_q_kd
avatar_gofa2_joint_5_q_kd = avatar_gofa1_joint_5_q_kd
avatar_gofa2_joint_6_q_kd = avatar_gofa1_joint_6_q_kd

avatar_rh_WRJ2_q_kd = avatar_lh_WRJ2_q_kd
avatar_rh_WRJ1_q_kd = avatar_lh_WRJ1_q_kd
avatar_rh_FFJ4_q_kd = avatar_lh_FFJ4_q_kd
avatar_rh_FFJ3_q_kd = avatar_lh_FFJ3_q_kd
avatar_rh_FFJ2_q_kd = avatar_lh_FFJ2_q_kd
avatar_rh_FFJ1_q_kd = avatar_lh_FFJ1_q_kd
avatar_rh_MFJ4_q_kd = avatar_lh_MFJ4_q_kd
avatar_rh_MFJ3_q_kd = avatar_lh_MFJ3_q_kd
avatar_rh_MFJ2_q_kd = avatar_lh_MFJ2_q_kd
avatar_rh_MFJ1_q_kd = avatar_lh_MFJ1_q_kd
avatar_rh_RFJ4_q_kd = avatar_lh_RFJ4_q_kd
avatar_rh_RFJ3_q_kd = avatar_lh_RFJ3_q_kd
avatar_rh_RFJ2_q_kd = avatar_lh_RFJ2_q_kd
avatar_rh_RFJ1_q_kd = avatar_lh_RFJ1_q_kd
avatar_rh_LFJ5_q_kd = avatar_lh_LFJ5_q_kd
avatar_rh_LFJ4_q_kd = avatar_lh_LFJ4_q_kd
avatar_rh_LFJ3_q_kd = avatar_lh_LFJ3_q_kd
avatar_rh_LFJ2_q_kd = avatar_lh_LFJ2_q_kd
avatar_rh_LFJ1_q_kd = avatar_lh_LFJ1_q_kd
avatar_rh_THJ5_q_kd = avatar_lh_THJ5_q_kd
avatar_rh_THJ4_q_kd = avatar_lh_THJ4_q_kd
avatar_rh_THJ3_q_kd = avatar_lh_THJ3_q_kd
avatar_rh_THJ2_q_kd = avatar_lh_THJ2_q_kd
avatar_rh_THJ1_q_kd = avatar_lh_THJ1_q_kd
#----------------------------------------assign Kp-----------------------------------------------------
Kp[0, 0] = avatar_gofa1_joint_1_q_kp
Kp[1, 0] = avatar_gofa1_joint_2_q_kp
Kp[2, 0] = avatar_gofa1_joint_3_q_kp
Kp[3, 0] = avatar_gofa1_joint_4_q_kp
Kp[4, 0] = avatar_gofa1_joint_5_q_kp
Kp[5, 0] = avatar_gofa1_joint_6_q_kp

Kp[6, 0] = avatar_lh_WRJ2_q_kp
Kp[7, 0] = avatar_lh_WRJ1_q_kp
Kp[8, 0] = avatar_lh_FFJ4_q_kp
Kp[9, 0] = avatar_lh_FFJ3_q_kp
Kp[10, 0] = avatar_lh_FFJ2_q_kp
Kp[11, 0] = avatar_lh_FFJ1_q_kp
Kp[12, 0] = avatar_lh_MFJ4_q_kp
Kp[13, 0] = avatar_lh_MFJ3_q_kp
Kp[14, 0] = avatar_lh_MFJ2_q_kp
Kp[15, 0] = avatar_lh_MFJ1_q_kp
Kp[16, 0] = avatar_lh_RFJ4_q_kp
Kp[17, 0] = avatar_lh_RFJ3_q_kp
Kp[18, 0] = avatar_lh_RFJ2_q_kp
Kp[19, 0] = avatar_lh_RFJ1_q_kp
Kp[20, 0] = avatar_lh_LFJ5_q_kp
Kp[21, 0] = avatar_lh_LFJ4_q_kp
Kp[22, 0] = avatar_lh_LFJ3_q_kp
Kp[23, 0] = avatar_lh_LFJ2_q_kp
Kp[24, 0] = avatar_lh_LFJ1_q_kp
Kp[25, 0] = avatar_lh_THJ5_q_kp
Kp[26, 0] = avatar_lh_THJ4_q_kp
Kp[27, 0] = avatar_lh_THJ3_q_kp
Kp[28, 0] = avatar_lh_THJ2_q_kp
Kp[29, 0] = avatar_lh_THJ1_q_kp

Kp[30, 0] = avatar_gofa2_joint_1_q_kp
Kp[31, 0] = avatar_gofa2_joint_2_q_kp
Kp[32, 0] = avatar_gofa2_joint_3_q_kp
Kp[33, 0] = avatar_gofa2_joint_4_q_kp
Kp[34, 0] = avatar_gofa2_joint_5_q_kp
Kp[35, 0] = avatar_gofa2_joint_6_q_kp

Kp[36, 0] = avatar_rh_WRJ2_q_kp
Kp[37, 0] = avatar_rh_WRJ1_q_kp
Kp[38, 0] = avatar_rh_FFJ4_q_kp
Kp[39, 0] = avatar_rh_FFJ3_q_kp
Kp[40, 0] = avatar_rh_FFJ2_q_kp
Kp[41, 0] = avatar_rh_FFJ1_q_kp
Kp[42, 0] = avatar_rh_MFJ4_q_kp
Kp[43, 0] = avatar_rh_MFJ3_q_kp
Kp[44, 0] = avatar_rh_MFJ2_q_kp
Kp[45, 0] = avatar_rh_MFJ1_q_kp
Kp[46, 0] = avatar_rh_RFJ4_q_kp
Kp[47, 0] = avatar_rh_RFJ3_q_kp
Kp[48, 0] = avatar_rh_RFJ2_q_kp
Kp[49, 0] = avatar_rh_RFJ1_q_kp
Kp[50, 0] = avatar_rh_LFJ5_q_kp
Kp[51, 0] = avatar_rh_LFJ4_q_kp
Kp[52, 0] = avatar_rh_LFJ3_q_kp
Kp[53, 0] = avatar_rh_LFJ2_q_kp
Kp[54, 0] = avatar_rh_LFJ1_q_kp
Kp[55, 0] = avatar_rh_THJ5_q_kp
Kp[56, 0] = avatar_rh_THJ4_q_kp
Kp[57, 0] = avatar_rh_THJ3_q_kp
Kp[58, 0] = avatar_rh_THJ2_q_kp
Kp[59, 0] = avatar_rh_THJ1_q_kp

Kp[60, 0] = avatar_xarm6_joint1_q_kp
Kp[61, 0] = avatar_xarm6_joint2_q_kp
Kp[62, 0] = avatar_xarm6_joint3_q_kp
Kp[63, 0] = avatar_xarm6_joint4_q_kp
Kp[64, 0] = avatar_xarm6_joint5_q_kp
Kp[65, 0] = avatar_xarm6_joint6_q_kp

#----------------------------------------assign Ki-----------------------------------------------------
Ki[0, 0] = avatar_gofa1_joint_1_q_ki
Ki[1, 0] = avatar_gofa1_joint_2_q_ki
Ki[2, 0] = avatar_gofa1_joint_3_q_ki
Ki[3, 0] = avatar_gofa1_joint_4_q_ki
Ki[4, 0] = avatar_gofa1_joint_5_q_ki
Ki[5, 0] = avatar_gofa1_joint_6_q_ki

Ki[6, 0] = avatar_lh_WRJ2_q_ki
Ki[7, 0] = avatar_lh_WRJ1_q_ki
Ki[8, 0] = avatar_lh_FFJ4_q_ki
Ki[9, 0] = avatar_lh_FFJ3_q_ki
Ki[10, 0] = avatar_lh_FFJ2_q_ki
Ki[11, 0] = avatar_lh_FFJ1_q_ki
Ki[12, 0] = avatar_lh_MFJ4_q_ki
Ki[13, 0] = avatar_lh_MFJ3_q_ki
Ki[14, 0] = avatar_lh_MFJ2_q_ki
Ki[15, 0] = avatar_lh_MFJ1_q_ki
Ki[16, 0] = avatar_lh_RFJ4_q_ki
Ki[17, 0] = avatar_lh_RFJ3_q_ki
Ki[18, 0] = avatar_lh_RFJ2_q_ki
Ki[19, 0] = avatar_lh_RFJ1_q_ki
Ki[20, 0] = avatar_lh_LFJ5_q_ki
Ki[21, 0] = avatar_lh_LFJ4_q_ki
Ki[22, 0] = avatar_lh_LFJ3_q_ki
Ki[23, 0] = avatar_lh_LFJ2_q_ki
Ki[24, 0] = avatar_lh_LFJ1_q_ki
Ki[25, 0] = avatar_lh_THJ5_q_ki
Ki[26, 0] = avatar_lh_THJ4_q_ki
Ki[27, 0] = avatar_lh_THJ3_q_ki
Ki[28, 0] = avatar_lh_THJ2_q_ki
Ki[29, 0] = avatar_lh_THJ1_q_ki

Ki[30, 0] = avatar_gofa2_joint_1_q_ki
Ki[31, 0] = avatar_gofa2_joint_2_q_ki
Ki[32, 0] = avatar_gofa2_joint_3_q_ki
Ki[33, 0] = avatar_gofa2_joint_4_q_ki
Ki[34, 0] = avatar_gofa2_joint_5_q_ki
Ki[35, 0] = avatar_gofa2_joint_6_q_ki

Ki[36, 0] = avatar_rh_WRJ2_q_ki
Ki[37, 0] = avatar_rh_WRJ1_q_ki
Ki[38, 0] = avatar_rh_FFJ4_q_ki
Ki[39, 0] = avatar_rh_FFJ3_q_ki
Ki[40, 0] = avatar_rh_FFJ2_q_ki
Ki[41, 0] = avatar_rh_FFJ1_q_ki
Ki[42, 0] = avatar_rh_MFJ4_q_ki
Ki[43, 0] = avatar_rh_MFJ3_q_ki
Ki[44, 0] = avatar_rh_MFJ2_q_ki
Ki[45, 0] = avatar_rh_MFJ1_q_ki
Ki[46, 0] = avatar_rh_RFJ4_q_ki
Ki[47, 0] = avatar_rh_RFJ3_q_ki
Ki[48, 0] = avatar_rh_RFJ2_q_ki
Ki[49, 0] = avatar_rh_RFJ1_q_ki
Ki[50, 0] = avatar_rh_LFJ5_q_ki
Ki[51, 0] = avatar_rh_LFJ4_q_ki
Ki[52, 0] = avatar_rh_LFJ3_q_ki
Ki[53, 0] = avatar_rh_LFJ2_q_ki
Ki[54, 0] = avatar_rh_LFJ1_q_ki
Ki[55, 0] = avatar_rh_THJ5_q_ki
Ki[56, 0] = avatar_rh_THJ4_q_ki
Ki[57, 0] = avatar_rh_THJ3_q_ki
Ki[58, 0] = avatar_rh_THJ2_q_ki
Ki[59, 0] = avatar_rh_THJ1_q_ki

Ki[60, 0] = avatar_xarm6_joint1_q_ki
Ki[61, 0] = avatar_xarm6_joint2_q_ki
Ki[62, 0] = avatar_xarm6_joint3_q_ki
Ki[63, 0] = avatar_xarm6_joint4_q_ki
Ki[64, 0] = avatar_xarm6_joint5_q_ki
Ki[65, 0] = avatar_xarm6_joint6_q_ki

#----------------------------------------assign Kd-----------------------------------------------------
Kd[0, 0] = avatar_gofa1_joint_1_q_kd
Kd[1, 0] = avatar_gofa1_joint_2_q_kd
Kd[2, 0] = avatar_gofa1_joint_3_q_kd
Kd[3, 0] = avatar_gofa1_joint_4_q_kd
Kd[4, 0] = avatar_gofa1_joint_5_q_kd
Kd[5, 0] = avatar_gofa1_joint_6_q_kd

Kd[6, 0] = avatar_lh_WRJ2_q_kd
Kd[7, 0] = avatar_lh_WRJ1_q_kd
Kd[8, 0] = avatar_lh_FFJ4_q_kd
Kd[9, 0] = avatar_lh_FFJ3_q_kd
Kd[10, 0] = avatar_lh_FFJ2_q_kd
Kd[11, 0] = avatar_lh_FFJ1_q_kd
Kd[12, 0] = avatar_lh_MFJ4_q_kd
Kd[13, 0] = avatar_lh_MFJ3_q_kd
Kd[14, 0] = avatar_lh_MFJ2_q_kd
Kd[15, 0] = avatar_lh_MFJ1_q_kd
Kd[16, 0] = avatar_lh_RFJ4_q_kd
Kd[17, 0] = avatar_lh_RFJ3_q_kd
Kd[18, 0] = avatar_lh_RFJ2_q_kd
Kd[19, 0] = avatar_lh_RFJ1_q_kd
Kd[20, 0] = avatar_lh_LFJ5_q_kd
Kd[21, 0] = avatar_lh_LFJ4_q_kd
Kd[22, 0] = avatar_lh_LFJ3_q_kd
Kd[23, 0] = avatar_lh_LFJ2_q_kd
Kd[24, 0] = avatar_lh_LFJ1_q_kd
Kd[25, 0] = avatar_lh_THJ5_q_kd
Kd[26, 0] = avatar_lh_THJ4_q_kd
Kd[27, 0] = avatar_lh_THJ3_q_kd
Kd[28, 0] = avatar_lh_THJ2_q_kd
Kd[29, 0] = avatar_lh_THJ1_q_kd

Kd[30, 0] = avatar_gofa2_joint_1_q_kd
Kd[31, 0] = avatar_gofa2_joint_2_q_kd
Kd[32, 0] = avatar_gofa2_joint_3_q_kd
Kd[33, 0] = avatar_gofa2_joint_4_q_kd
Kd[34, 0] = avatar_gofa2_joint_5_q_kd
Kd[35, 0] = avatar_gofa2_joint_6_q_kd

Kd[36, 0] = avatar_rh_WRJ2_q_kd
Kd[37, 0] = avatar_rh_WRJ1_q_kd
Kd[38, 0] = avatar_rh_FFJ4_q_kd
Kd[39, 0] = avatar_rh_FFJ3_q_kd
Kd[40, 0] = avatar_rh_FFJ2_q_kd
Kd[41, 0] = avatar_rh_FFJ1_q_kd
Kd[42, 0] = avatar_rh_MFJ4_q_kd
Kd[43, 0] = avatar_rh_MFJ3_q_kd
Kd[44, 0] = avatar_rh_MFJ2_q_kd
Kd[45, 0] = avatar_rh_MFJ1_q_kd
Kd[46, 0] = avatar_rh_RFJ4_q_kd
Kd[47, 0] = avatar_rh_RFJ3_q_kd
Kd[48, 0] = avatar_rh_RFJ2_q_kd
Kd[49, 0] = avatar_rh_RFJ1_q_kd
Kd[50, 0] = avatar_rh_LFJ5_q_kd
Kd[51, 0] = avatar_rh_LFJ4_q_kd
Kd[52, 0] = avatar_rh_LFJ3_q_kd
Kd[53, 0] = avatar_rh_LFJ2_q_kd
Kd[54, 0] = avatar_rh_LFJ1_q_kd
Kd[55, 0] = avatar_rh_THJ5_q_kd
Kd[56, 0] = avatar_rh_THJ4_q_kd
Kd[57, 0] = avatar_rh_THJ3_q_kd
Kd[58, 0] = avatar_rh_THJ2_q_kd
Kd[59, 0] = avatar_rh_THJ1_q_kd

Kd[60, 0] = avatar_xarm6_joint1_q_kd
Kd[61, 0] = avatar_xarm6_joint2_q_kd
Kd[62, 0] = avatar_xarm6_joint3_q_kd
Kd[63, 0] = avatar_xarm6_joint4_q_kd
Kd[64, 0] = avatar_xarm6_joint5_q_kd
Kd[65, 0] = avatar_xarm6_joint6_q_kd
